export const CREATE_BOARD = 'CREATE_BOARD';
export const GET_BOARDS = 'GET_BOARDS';
export const GET_BOARD = 'GET_BOARD';
export const REARRANGE_BOARD_COLUMNS = 'REARRANGE_BOARD_COLUMNS';
export const UPDATE_BOARD_COLUMNS = 'UPDATE_BOARD_COLUMNS';
export const DELETE_BOARD = 'DELETE_BOARD';

export const CREATE_COLUMN = 'CREATE_COLUMN';
export const GET_COLUMNS = 'GET_COLUMNS';
// export const GET_COLUMNS_ORDER = 'GET_COLUMNS_ORDER';
export const UPDATE_COLUMN_TASK = 'UPDATE_COLUMN_TASK';
export const REARRANGE_COLUMN_TASKS = 'REARRANGE_COLUMN_TASKS';

export const DELETE_COLUMN = 'DELETE_COLUMN';
export const DELETE_ALL_BOARD_COLUMNS = 'DELETE_ALL_BOARD_COLUMNS';

export const CREATE_TASK = 'CREATE_TASK';
export const GET_TASKS = 'GET_TASKS';
export const DELETE_TASK = 'DELETE_TASK';
export const DELETE_ALL_COLUMN_TASKS = 'DELETE_ALL_COLUMN_TASKS';


export const SIGNIN = 'SIGNIN';
export const SIGNUP = 'SIGNUP';
export const LOGOUT = 'LOGOUT';
export const LOGIN_WITH_TOKEN = 'LOGIN_WITH_TOKEN';